# -*- coding: utf-8 -*-
"""CLP-II Week1 Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17s0inLZQrWF2B1xkJHsiBr1zkOo1IlGW

###1. Import Dataset and Load Data
"""

#Step 1:Import the dataset
import pandas as pd
df = pd.read_csv('/content/breast-cancer.csv')

#PrevieW of first 5 rowswhich is default,but we can \choose as much rows
df.head()

"""###2. Data Cleansing and Preprocessing
Step2 A:Checking Dataset Info
"""

#Step 2:Data Cleaning & Preprocessing
#Step2 A:Checking basic info
df.info()
df.head()

"""Step2 B:Missing Values"""

#Checkng for missing values
df.isnull().sum()

"""Step2 C: Duplicates"""

#Drop duplicate rows if any
df = df.drop_duplicates()

"""Step2 D:Handle Missing Values"""

#Fill missing values (example: with mean for numeric columns)
df = df.fillna(df.mean(numeric_only=True))

"""Step2 E:Reset Index"""

#Reset index after cleaning
df.reset_index(drop=True, inplace=True)

"""Step2 F: Confirm Cleaning"""

#Confirm cleaning
df.info()

"""###3. Data Analysis
Step3 A: Dataset Overview
"""

#General info and first look of the dataset
df.info()
df.head()

#Check unique values in target column
df['diagnosis'].unique()

#Count of target classes
df['diagnosis'].value_counts(normalize=True) * 100  # percentage
#This shows class balance

"""Step3 B: Statistical Summary"""

#Summary of numerical features
df.describe()

"""Step3 C: Missing and Duplicate Data"""

#Missing values
df.isnull().sum()

#Duplicate rows
df.duplicated().sum()
#Ensures dataset integrity

"""Step3 D: Correlation and Key Features"""

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['diagnosis_encoded'] = le.fit_transform(df['diagnosis'])

#Correlation matrix (numeric only, including the newly encoded target variable)
corr_matrix = df.select_dtypes(include=['number']).corr()

#Top 5 features most correlated with target (diagnosis encoded)

corr_with_target = corr_matrix['diagnosis_encoded'].sort_values(ascending=False)
corr_with_target.head(10)
#Reveals which features are most predictive of cancer type.

"""Step3 E: Hidden Insights"""

#Group statistics by diagnosis
df.groupby('diagnosis').mean()

#Compare mean values of key features between malignant vs benign
important_features = ['radius_mean','texture_mean','perimeter_mean','area_mean']
df.groupby('diagnosis')[important_features].mean()
#Shows how malignant tumors differ numerically from benign ones.

"""Step3 F: Class Distribution"""

#Class Distribution
df['diagnosis'].value_counts(normalize=True) * 100

"""Step3 G: Feature Variability"""

#Feature Variability
df.std(numeric_only=True).sort_values(ascending=False).head(10)

"""Step3 H: Group Statistics"""

#Group Statistics
df.groupby('diagnosis').mean()

"""###4. Data VIsualization"""

#Step 4:Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

#Distribution of target variable
sns.countplot(x='diagnosis', data=df)
plt.title('Distribution of Diagnosis')
plt.show()

#Histogram of a numeric feature (example: radius_mean)
sns.histplot(df['radius_mean'], bins=30, kde=True)
plt.title('Distribution of Radius Mean')
plt.show()